---
title: "RWorksheet_Arlante#3a"
author: "Stephanie Lois Amber Arlante"
date: "2024-10-01"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
#Using Vectors

#1.LETTERS

#a. You need to produce a vector that contains the first 11 letters.

first11 <- LETTERS[1:11]
(first11)
```



```{r}

#b. Produce a vector that contains the odd numbered letters.

oddletters <- LETTERS[seq(1,26, by = 2)]
(oddletters)
```


```{r}

#c. Produce a vector that contains the vowels

vowels <- LETTERS[c(1, 5, 9, 15, 21)]
(vowels)
```


{r}

#d. Produce a vector that contains the last 5 lowercase letters.

last5lower <- letters[22:26]
(last5lower)



```{r}

#e. Produce a vector that contains letters between 15 to 24 letters in lowercase.

lower15_24 <- letters[15:24]
(lower15_24)
```


```{r}

#2. Vector of Temperature.


#a. Character of cities

city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")

(city)
```


```{r}

#b. Vectors of Temperature 

temp <- c(42, 39, 34, 34, 30, 27)
(temp)
```


```{r}

#c. Data frame to combine the city and the temp

citytemp <- data.frame(City = city, Tempreture = temp)

(citytemp)

```

```{r}

#d. rename the columns using the names() function

names(citytemp) <- c("City", "Tempreture")
(citytemp)

```

{r}

#e. Print the structure by using str() function.

str(citytemp) 
#outputs the structure of citytemp



```{r}

#f. The content of row 3 and row 4.

(citytemp[3:4, ])
```


```{r}

#g. Display the city with highest temperature and the city with the lowest temperature.

(citytemp[which.max(citytemp$Tempreture), ])


(citytemp[which.min(citytemp$Tempreture), ])
```


```{r}
#Using Matrices
#2. Create a matrix of one to eight and eleven to fourteen with four columns and three rows.
#2a. 
matrix_data <- matrix(c(1:8, 11:14), nrow = 3, ncol = 4)
matrix_data
```
```{r}
#2b
matrix_multiplied <- matrix_data * 2
matrix_multiplied

```
```{r}
#2c
row_2 <- matrix_data[2, ]
row_2

```
```{r}
#2d
subset_matrix <- matrix_data[1:2, 3:4]
subset_matrix

```
```{r}
#2e
row_3_subset <- matrix_data[3, 2:3]
row_3_subset

```
```{r}
#2f
column_4 <- matrix_data[, 4]
column_4

```
```{r}
#2g
dimnames(matrix_multiplied) <- list(c("isa", "dalawa", "tatlo"), c("uno", "dos", "tres", "quatro"))
matrix_multiplied

```
```{r}
#2h
dim(matrix_data) <- c(6, 2)
matrix_data

```
```{r}
#Using Arrays
#3a

values <- rep(c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1), times = 2)

my_array <- array(values, dim = c(2, 4, 3))
my_array

```
```{r}
#3b
dim(my_array)

```
```{r}
#3c

row_names <- c("a", "b")
column_names <- c("A", "B", "C", "D")

dimension_names <- c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array")

dimnames(my_array) <- list(row_names, column_names, dimension_names)

my_array

```
