---
title: "RWorksheet_lastname#2"
author: "Stephanie Lois Amber Arlante"
date: "2024-09-25"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
#1. Create a vector using : operator 
#a. Sequence from -5 to 5. Write the R code and its output.Describe its output.

seq_a <- c(-5:5)
print(seq_a)
```
```{r}
#b. x <- 1:7. What will be the value of x?

x <- 1:7
print(x)

```
```{r}
#2. Create a vector using seq() function

#a. seq(1, 3, by=0.2) # specify step size. Write the R script and its output. Describe the output.

seq_a <- seq(1, 3, by = 0.2)
print(seq_a)

```
```{r}
#3. A factory has a census of its workers. There are 50 workers in total. The following


#a. Access 3rd element, what is the value?

ages <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35, 24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26, 18)

third_element <- ages[3]
print(third_element)

```
```{r}
#b. Access 2nd and 4th element, what are the values?

second_fourth_elements <- ages[c(2, 4)]
print(second_fourth_elements)

```
```{r}
exclude_4th_12th <- ages[-c(4, 12)]
print(exclude_4th_12th)

```
```{r}
#4. *Create a vector x <- c("first"=3, "second"=0, "third"=9). Then named the vector, names(x).

x <- c("first" = 3, "second" = 0, "third" = 9)
print(x)
result <- x[c("first", "third")]
print(result)

```
```{r}
#5. Create a sequence x from -3:2.
x <- -3:2
x[2] <- 0
print(x)

```
```{r}
#6. *The following data shows the diesel fuel purchased by Mr. Cruz.

month = c("jan", "fed", "Mar", "Apr", "May", "june")
price_per_liter = c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
purchase_quality = c(25, 30, 40, 50, 10, 45)

df <- data.frame(Month = month, PriceperLiter = price_per_liter, PurchaseQuality = purchase_quality)
print(df)
```
```{r}
#7. 
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers), sd(rivers), min(rivers), max(rivers))
print(data)

```
```{r}
#: 8. The table below gives the 25 most powerful celebrities and their annual pay as ranked by the editions of Forbes magazine and as listed on the Forbes.com website.

#a.) Create vectors according to the table
powerRanking <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
celebrityName <- c("Tom Cruise", "Rolling Stones", "Oprah Winfrey", "U2", "Tiger Woods", "Steven Spielberg", "Howard Stem", "50 Cent", "Cast of the Sopranos", "Dan Brown", "Bruce Springsteen", "Donald Trump", "Muhammad Ali", "Paul McCartney", "George Lucas", "Elton John", "David Letterman", "Phil Mickelson", "J.K. Rowling", "Bradd Pitt", "Peter Jackson", "Dr. Phil McGraw", "Jay Lenon", "Celine Dion", "Kobe Bryant")
pay <- c(67, 90, 225, 110, 90, 332, 302, 41, 52, 88, 55, 44, 55, 40, 233, 34, 40, 47, 75, 25, 39, 45, 32, 40, 31)

celeb <- data.frame(PowerRanking = powerRanking, Celebrity = celebrityName, Pay = pay)
print(celeb)

#b.) Modify power ranking and pay of J.K. Rowling and change power ranking to 15 and pay to 90
powerRanking[19] <- 15
pay[75] <- 90
celeb <- data.frame(PowerRanking = powerRanking, Celebrity = celebrityName, Pay = pay)
print(celeb)

#c.) Create an excel file
write.csv(celeb, file = "PowerRanking.csv", row.names = FALSE)
importedData <- read.csv("PowerRanking.csv")
print(importedData)

#d.) Access the rows 10 to 20 
ranksData <- celeb[10:20, ]
save(ranksData, file = "Ranks.Data")
print(ranksData)

#e.) It displays the rows 10 to 20 in a separate file.

```
```{r}
#9.Download the Hotels-Vienna https://tinyurl.com/Hotels-Vienna

#a. Import the excel file into your RStudio. What is the R script?

library(readxl)


hotels_vienna <- read_excel("/cloud/project/hotels-vienna.xlsx")  

# b. How many dimensions does the dataset have? What is the R script? WHat is its output?

library(readxl)
hotels_vienna <- read_excel("/cloud/project/hotels-vienna.xlsx")

dimensions <- dim(hotels_vienna)
print(dimensions)
```

#c. Select columns country, neighborhood,price, stars, accommodation_type, andratings. Write the R script.
```{r}
library(readxl)
hotels_vienna <- read_excel("/cloud/project/hotels-vienna.xlsx")

library(dplyr)
selected_columns <- hotels_vienna %>%
  select(country, neighbourhood, price, stars, accommodation_type, rating)
print(selected_columns)
```
#d. Save the data as **new.RData to your RStudio. Write the R script.

```{r}
library(readxl)
hotels_vienna <- read_excel("/cloud/project/hotels-vienna.xlsx")

save(hotels_vienna, file = "new.RData")

```
#e. Display the first six rows and last six rows of the new.R Data. What is the R script?
```{r}
load("new.RData")
print(head(hotels_vienna))
print(tail(hotels_vienna))

```
